#!/bin/bash

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  . ~/.jenkins.sh
fi

# Function to cleanup any running instances and exit
function clean_up_and_exit {
  ruby ./script/cleanup.sh
  exit $1
}

# Set Ruby / Gemset
rvm use 1.9.3-p327@omnibus-heirloom --create

# Install knife ec2
gem install knife-ec2 --no-ri --no-rdoc
if [ $? -ne 0 ]; then
  clean_up_and_exit(1)
fi

# Create an instance
knife ec2 server create -c ./script/knife/config/knife.rb \
                        --template-file ./script/knife/templates/omnibus.erb \
                        --groups=build \
                        --node-name='heirloom-omnibus-build'
if [ $? -ne 0 ]; then
  clean_up_and_exit(1)
fi

clean_up_and_exit(0)
