#!/bin/bash

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  . ~/.jenkins.sh
fi

# Set Ruby / Gemset
rvm use 1.9.3-p327@omnibus-heirloom --create

# Exit On Any Error
set -e

# Install bundle
bundle

# Clean up old builds
bundle exec rake clean

# Build heirloom rpm
bundle exec rake projects:heirloom
