#!/bin/bash

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  . ~/.jenkins.sh
fi

# Set Ruby / Gemset
rvm use 1.9.3-p327@omnibus-heirloom --create

# Exit On Any Error
set -e

# Install knife ec2
gem install knife-ec2 --no-ri --no-rdoc

# Create an instance
knife ec2 server create -c ./script/knife/config/knife.rb --template-file=./script/knife/templates/omnibus.erb --groups=build
